/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CeloWordGame } from "./CeloWordGame";
export * as factories from "./factories";
export { CeloWordGame__factory } from "./factories/CeloWordGame__factory";
