/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { CeloWordGame, CeloWordGameInterface } from "../CeloWordGame";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "score",
        type: "uint256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "score",
        type: "uint256",
      },
    ],
    name: "submitScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101b6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063aff0b2971461003b578063d47875d014610050575b600080fd5b61004e610049366004610137565b61008b565b005b61007961005e366004610150565b6001600160a01b031660009081526020819052604090205490565b60405190815260200160405180910390f35b600081116100d85760405162461bcd60e51b815260206004820152601660248201527553636f7265206d75737420626520706f73697469766560501b604482015260640160405180910390fd5b3360009081526020819052604090205481111561013457336000818152602081815260409182902084905590518381527f66ead48cfe0e1d1aa8bad492e906c348dfcfeecbf3b7b2cdf9b1f3cfa42a2945910160405180910390a25b50565b60006020828403121561014957600080fd5b5035919050565b60006020828403121561016257600080fd5b81356001600160a01b038116811461017957600080fd5b939250505056fea2646970667358221220ca806513021b40afecb13cf98f56bed4a812df6ff2ec3f324e106f4f9d20108264736f6c63430008140033";

type CeloWordGameConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CeloWordGameConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CeloWordGame__factory extends ContractFactory {
  constructor(...args: CeloWordGameConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CeloWordGame & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CeloWordGame__factory {
    return super.connect(runner) as CeloWordGame__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CeloWordGameInterface {
    return new Interface(_abi) as CeloWordGameInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CeloWordGame {
    return new Contract(address, _abi, runner) as unknown as CeloWordGame;
  }
}
